const options = [
  { label: 'Açaí', value: 'Açaí' },
  { label: 'Apple', value: 'Apple' },
  { label: 'Akee', value: 'Akee' },
  { label: 'Apricot', value: 'Apricot' },
  { label: 'Avocado', value: 'Avocado' },
  { label: 'Banana', value: 'Banana' },
  { label: 'Bilberry', value: 'Bilberry' },
  { label: 'Blackberry', value: 'Blackberry' },
  { label: 'Blackcurrant', value: 'Blackcurrant' },
  { label: 'Black sapote', value: 'Black sapote' },
  { label: 'Blueberry', value: 'Blueberry' },
  { label: 'Boysenberry', value: 'Boysenberry' },
  { label: "Buddha's hand", value: "Buddha's hand" },
  { label: 'Crab apples', value: 'Crab apples' },
  { label: 'Currant', value: 'Currant' },
  { label: 'Cherry', value: 'Cherry' },
  { label: 'Cherimoya', value: 'Cherimoya' },
  { label: 'Chico fruit', value: 'Chico fruit' },
  { label: 'Cloudberry', value: 'Cloudberry' },
  { label: 'Coconut', value: 'Coconut' },
  { label: 'Cranberry', value: 'Cranberry' },
  { label: 'Cucumber', value: 'Cucumber' },
  { label: 'Damson', value: 'Damson' },
  { label: 'Date', value: 'Date' },
  { label: 'Dragonfruit', value: 'Dragonfruit' },
  { label: 'Pitaya', value: 'Pitaya' },
  { label: 'Durian', value: 'Durian' },
  { label: 'Elderberry', value: 'Elderberry' },
  { label: 'Feijoa', value: 'Feijoa' },
  { label: 'Fig', value: 'Fig' },
  { label: 'Goji berry', value: 'Goji berry' },
  { label: 'Gooseberry', value: 'Gooseberry' },
  { label: 'Grape', value: 'Grape' },
  { label: 'Raisin', value: 'Raisin' },
  { label: 'Grapefruit', value: 'Grapefruit' },
  { label: 'Guava', value: 'Guava' },
  { label: 'Honeyberry', value: 'Honeyberry' },
  { label: 'Huckleberry', value: 'Huckleberry' },
  { label: 'Jabuticaba', value: 'Jabuticaba' },
  { label: 'Jackfruit', value: 'Jackfruit' },
  { label: 'Jambul', value: 'Jambul' },
  { label: 'Japanese plum', value: 'Japanese plum' },
  { label: 'Jostaberry', value: 'Jostaberry' },
  { label: 'Jujube', value: 'Jujube' },
  { label: 'Juniper berry', value: 'Juniper berry' },
  { label: 'Kiwano', value: 'Kiwano' },
  { label: 'Kiwifruit', value: 'Kiwifruit' },
  { label: 'Kumquat', value: 'Kumquat' },
  { label: 'Lemon', value: 'Lemon' },
  { label: 'Lime', value: 'Lime' },
  { label: 'Loquat', value: 'Loquat' },
  { label: 'Longan', value: 'Longan' },
  { label: 'Lychee', value: 'Lychee' },
  { label: 'Mango', value: 'Mango' },
  { label: 'Mangosteen', value: 'Mangosteen' },
  { label: 'Marionberry', value: 'Marionberry' },
  { label: 'Melon', value: 'Melon' },
  { label: 'Cantaloupe', value: 'Cantaloupe' },
  { label: 'Honeydew', value: 'Honeydew' },
  { label: 'Watermelon', value: 'Watermelon' },
  { label: 'Miracle fruit', value: 'Miracle fruit' },
  { label: 'Mulberry', value: 'Mulberry' },
  { label: 'Nectarine', value: 'Nectarine' },
  { label: 'Nance', value: 'Nance' },
  { label: 'Olive', value: 'Olive' },
  { label: 'Orange', value: 'Orange' },
  { label: 'Blood orange', value: 'Blood orange' },
  { label: 'Clementine', value: 'Clementine' },
  { label: 'Mandarine', value: 'Mandarine' },
  { label: 'Tangerine', value: 'Tangerine' },
  { label: 'Papaya', value: 'Papaya' },
  { label: 'Passionfruit', value: 'Passionfruit' },
  { label: 'Peach', value: 'Peach' },
  { label: 'Pear', value: 'Pear' },
  { label: 'Persimmon', value: 'Persimmon' },
  { label: 'Plantain', value: 'Plantain' },
  { label: 'Plum', value: 'Plum' },
  { label: 'Prune', value: 'Prune' },
  { label: 'Pineapple', value: 'Pineapple' },
  { label: 'Pineberry', value: 'Pineberry' },
  { label: 'Plumcot', value: 'Plumcot' },
  { label: 'Pomegranate', value: 'Pomegranate' },
  { label: 'Pomelo', value: 'Pomelo' },
  { label: 'Purple mangosteen', value: 'Purple mangosteen' },
  { label: 'Quince', value: 'Quince' },
  { label: 'Raspberry', value: 'Raspberry' },
  { label: 'Salmonberry', value: 'Salmonberry' },
  { label: 'Rambutan', value: 'Rambutan' },
  { label: 'Redcurrant', value: 'Redcurrant' },
  { label: 'Salal', value: 'Salal' },
  { label: 'Salak', value: 'Salak' },
  { label: 'Satsuma', value: 'Satsuma' },
  { label: 'Soursop', value: 'Soursop' },
  { label: 'Star apple', value: 'Star apple' },
  { label: 'Star fruit', value: 'Star fruit' },
  { label: 'Strawberry', value: 'Strawberry' },
  { label: 'Surinam cherry', value: 'Surinam cherry' },
  { label: 'Tamarillo', value: 'Tamarillo' },
  { label: 'Tamarind', value: 'Tamarind' },
  { label: 'Ugli fruit', value: 'Ugli fruit' },
  { label: 'White currant', value: 'White currant' },
  { label: 'White sapote', value: 'White sapote' },
  { label: 'Yuzu', value: 'Yuzu' },
  { label: 'Avocado', value: 'Avocado' },
  { label: 'Bell pepper', value: 'Bell pepper' },
  { label: 'Chili pepper', value: 'Chili pepper' },
  { label: 'Corn kernel', value: 'Corn kernel' },
  { label: 'Cucumber', value: 'Cucumber' },
  { label: 'Eggplant', value: 'Eggplant' },
  { label: 'Olive', value: 'Olive' },
  { label: 'Pea', value: 'Pea' },
  { label: 'Pumpkin', value: 'Pumpkin' },
  { label: 'Squash', value: 'Squash' },
  { label: 'Tomato', value: 'Tomato' },
  { label: 'Zucchini', value: 'Zucchini' },
];

export default options;
